language: go

go:
  - "1.10"
  - "1.11"
  - "1.12"
  - "1.13"

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)